name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Name of the AKS Cluster"
        required: true
        default: "MyAKSCluster1"
      resource_group:
        description: "Resource Group"
        required: true
        default: "AKS_RG2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} \
                   -p ${{ secrets.ARM_CLIENT_SECRET }} \
                   --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ github.event.inputs.resource_group }} \
                                  --name ${{ github.event.inputs.cluster_name }} \
                                  --admin

      - name: Deploy application
        run: |
          kubectl apply -f k8s-manifests/deployment.yaml
          kubectl apply -f k8s-manifests/service.yaml

      - name: Deploy Ingress Controller
        run: |
          # Install Nginx Ingress Controller
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

      - name: Apply Ingress resource
        run: |
          kubectl apply -f k8s-manifests/ingress.yaml
