name: Terraform AKS Deployment

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Name of the AKS Cluster"
        required: true
        default: "my-cluster"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} \
                 -p ${{ secrets.ARM_CLIENT_SECRET }} \
                 --tenant ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve

    # Capture Terraform Outputs
    - name: Capture Terraform Outputs
      id: capture_outputs
      run: |
        # Capture outputs directly and remove surrounding quotes
        AKS_CLUSTER_NAME=$(terraform output aks_cluster_name | tr -d '"')
        RESOURCE_GROUP=$(terraform output aks_resource_group | tr -d '"')

        # Debugging outputs to verify correctness
        echo "AKS_CLUSTER_NAME=${AKS_CLUSTER_NAME}"
        echo "RESOURCE_GROUP=${RESOURCE_GROUP}"

        # Check if values are captured correctly
        if [ -z "$AKS_CLUSTER_NAME" ] || [ -z "$RESOURCE_GROUP" ]; then
          echo "Failed to capture AKS_CLUSTER_NAME or RESOURCE_GROUP"
          exit 1
        fi

        # Store the values in GITHUB_ENV
        echo "AKS_CLUSTER_NAME=${AKS_CLUSTER_NAME}" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=${RESOURCE_GROUP}" >> $GITHUB_ENV

    # Get AKS Credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} \
                               --name ${{ env.AKS_CLUSTER_NAME }} \
                               --admin

    # Set up Kubectl
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3

    # Deploy application to AKS
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s-manifests/deployment.yaml
        kubectl apply -f k8s-manifests/service.yaml
